services:
  synapse:
    build: .
    image: synapse
    container_name: synapse
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - GENAI_API_KEYS
      - OPENROUTER_API_KEY
      # Works on Mac (via Orbstack/Docker Desktop) and Linux (via host-gateway)
      - http_proxy=http://host.docker.internal:1087
      - https_proxy=http://host.docker.internal:1087
      - ALL_PROXY=socks5://host.docker.internal:1080
    restart: unless-stopped
