// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: generate.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Response_Type int32

const (
	Response_CHUNK     Response_Type = 0
	Response_KEEPALIVE Response_Type = 1
)

// Enum value maps for Response_Type.
var (
	Response_Type_name = map[int32]string{
		0: "CHUNK",
		1: "KEEPALIVE",
	}
	Response_Type_value = map[string]int32{
		"CHUNK":     0,
		"KEEPALIVE": 1,
	}
)

func (x Response_Type) Enum() *Response_Type {
	p := new(Response_Type)
	*p = x
	return p
}

func (x Response_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Response_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_generate_proto_enumTypes[0].Descriptor()
}

func (Response_Type) Type() protoreflect.EnumType {
	return &file_generate_proto_enumTypes[0]
}

func (x Response_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Response_Type.Descriptor instead.
func (Response_Type) EnumDescriptor() ([]byte, []int) {
	return file_generate_proto_rawDescGZIP(), []int{2, 0}
}

type GenerationConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Temperature   *float32               `protobuf:"fixed32,1,opt,name=temperature,proto3,oneof" json:"temperature,omitempty"`
	TopP          *float32               `protobuf:"fixed32,2,opt,name=top_p,json=topP,proto3,oneof" json:"top_p,omitempty"`
	TopK          *float32               `protobuf:"fixed32,3,opt,name=top_k,json=topK,proto3,oneof" json:"top_k,omitempty"`
	OutputLength  *int32                 `protobuf:"varint,4,opt,name=output_length,json=outputLength,proto3,oneof" json:"output_length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerationConfig) Reset() {
	*x = GenerationConfig{}
	mi := &file_generate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerationConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerationConfig) ProtoMessage() {}

func (x *GenerationConfig) ProtoReflect() protoreflect.Message {
	mi := &file_generate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerationConfig.ProtoReflect.Descriptor instead.
func (*GenerationConfig) Descriptor() ([]byte, []int) {
	return file_generate_proto_rawDescGZIP(), []int{0}
}

func (x *GenerationConfig) GetTemperature() float32 {
	if x != nil && x.Temperature != nil {
		return *x.Temperature
	}
	return 0
}

func (x *GenerationConfig) GetTopP() float32 {
	if x != nil && x.TopP != nil {
		return *x.TopP
	}
	return 0
}

func (x *GenerationConfig) GetTopK() float32 {
	if x != nil && x.TopK != nil {
		return *x.TopK
	}
	return 0
}

func (x *GenerationConfig) GetOutputLength() int32 {
	if x != nil && x.OutputLength != nil {
		return *x.OutputLength
	}
	return 0
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	ModelCode     string                 `protobuf:"bytes,2,opt,name=model_code,json=modelCode,proto3" json:"model_code,omitempty"`
	Stream        bool                   `protobuf:"varint,3,opt,name=stream,proto3" json:"stream,omitempty"`
	Config        *GenerationConfig      `protobuf:"bytes,4,opt,name=config,proto3,oneof" json:"config,omitempty"`
	Images        [][]byte               `protobuf:"bytes,5,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_generate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_generate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_generate_proto_rawDescGZIP(), []int{1}
}

func (x *Request) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *Request) GetModelCode() string {
	if x != nil {
		return x.ModelCode
	}
	return ""
}

func (x *Request) GetStream() bool {
	if x != nil {
		return x.Stream
	}
	return false
}

func (x *Request) GetConfig() *GenerationConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *Request) GetImages() [][]byte {
	if x != nil {
		return x.Images
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          Response_Type          `protobuf:"varint,1,opt,name=type,proto3,enum=synapse.Response_Type" json:"type,omitempty"`
	Chunk         string                 `protobuf:"bytes,2,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_generate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_generate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_generate_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetType() Response_Type {
	if x != nil {
		return x.Type
	}
	return Response_CHUNK
}

func (x *Response) GetChunk() string {
	if x != nil {
		return x.Chunk
	}
	return ""
}

type ListModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsRequest) Reset() {
	*x = ListModelsRequest{}
	mi := &file_generate_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsRequest) ProtoMessage() {}

func (x *ListModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_generate_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsRequest.ProtoReflect.Descriptor instead.
func (*ListModelsRequest) Descriptor() ([]byte, []int) {
	return file_generate_proto_rawDescGZIP(), []int{3}
}

type ListModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []string               `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsResponse) Reset() {
	*x = ListModelsResponse{}
	mi := &file_generate_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsResponse) ProtoMessage() {}

func (x *ListModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_generate_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsResponse.ProtoReflect.Descriptor instead.
func (*ListModelsResponse) Descriptor() ([]byte, []int) {
	return file_generate_proto_rawDescGZIP(), []int{4}
}

func (x *ListModelsResponse) GetModels() []string {
	if x != nil {
		return x.Models
	}
	return nil
}

var File_generate_proto protoreflect.FileDescriptor

const file_generate_proto_rawDesc = "" +
	"\n" +
	"\x0egenerate.proto\x12\asynapse\"\xcd\x01\n" +
	"\x10GenerationConfig\x12%\n" +
	"\vtemperature\x18\x01 \x01(\x02H\x00R\vtemperature\x88\x01\x01\x12\x18\n" +
	"\x05top_p\x18\x02 \x01(\x02H\x01R\x04topP\x88\x01\x01\x12\x18\n" +
	"\x05top_k\x18\x03 \x01(\x02H\x02R\x04topK\x88\x01\x01\x12(\n" +
	"\routput_length\x18\x04 \x01(\x05H\x03R\foutputLength\x88\x01\x01B\x0e\n" +
	"\f_temperatureB\b\n" +
	"\x06_top_pB\b\n" +
	"\x06_top_kB\x10\n" +
	"\x0e_output_length\"\xb3\x01\n" +
	"\aRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12\x1d\n" +
	"\n" +
	"model_code\x18\x02 \x01(\tR\tmodelCode\x12\x16\n" +
	"\x06stream\x18\x03 \x01(\bR\x06stream\x126\n" +
	"\x06config\x18\x04 \x01(\v2\x19.synapse.GenerationConfigH\x00R\x06config\x88\x01\x01\x12\x16\n" +
	"\x06images\x18\x05 \x03(\fR\x06imagesB\t\n" +
	"\a_config\"n\n" +
	"\bResponse\x12*\n" +
	"\x04type\x18\x01 \x01(\x0e2\x16.synapse.Response.TypeR\x04type\x12\x14\n" +
	"\x05chunk\x18\x02 \x01(\tR\x05chunk\" \n" +
	"\x04Type\x12\t\n" +
	"\x05CHUNK\x10\x00\x12\r\n" +
	"\tKEEPALIVE\x10\x01\"\x13\n" +
	"\x11ListModelsRequest\",\n" +
	"\x12ListModelsResponse\x12\x16\n" +
	"\x06models\x18\x01 \x03(\tR\x06models2\x8c\x01\n" +
	"\bGenerate\x127\n" +
	"\fGenerateTask\x12\x10.synapse.Request\x1a\x11.synapse.Response\"\x000\x01\x12G\n" +
	"\n" +
	"ListModels\x12\x1a.synapse.ListModelsRequest\x1a\x1b.synapse.ListModelsResponse\"\x00B%Z#github.com/sokinpui/synapse.go/grpcb\x06proto3"

var (
	file_generate_proto_rawDescOnce sync.Once
	file_generate_proto_rawDescData []byte
)

func file_generate_proto_rawDescGZIP() []byte {
	file_generate_proto_rawDescOnce.Do(func() {
		file_generate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_generate_proto_rawDesc), len(file_generate_proto_rawDesc)))
	})
	return file_generate_proto_rawDescData
}

var file_generate_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_generate_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_generate_proto_goTypes = []any{
	(Response_Type)(0),         // 0: synapse.Response.Type
	(*GenerationConfig)(nil),   // 1: synapse.GenerationConfig
	(*Request)(nil),            // 2: synapse.Request
	(*Response)(nil),           // 3: synapse.Response
	(*ListModelsRequest)(nil),  // 4: synapse.ListModelsRequest
	(*ListModelsResponse)(nil), // 5: synapse.ListModelsResponse
}
var file_generate_proto_depIdxs = []int32{
	1, // 0: synapse.Request.config:type_name -> synapse.GenerationConfig
	0, // 1: synapse.Response.type:type_name -> synapse.Response.Type
	2, // 2: synapse.Generate.GenerateTask:input_type -> synapse.Request
	4, // 3: synapse.Generate.ListModels:input_type -> synapse.ListModelsRequest
	3, // 4: synapse.Generate.GenerateTask:output_type -> synapse.Response
	5, // 5: synapse.Generate.ListModels:output_type -> synapse.ListModelsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_generate_proto_init() }
func file_generate_proto_init() {
	if File_generate_proto != nil {
		return
	}
	file_generate_proto_msgTypes[0].OneofWrappers = []any{}
	file_generate_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_generate_proto_rawDesc), len(file_generate_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_generate_proto_goTypes,
		DependencyIndexes: file_generate_proto_depIdxs,
		EnumInfos:         file_generate_proto_enumTypes,
		MessageInfos:      file_generate_proto_msgTypes,
	}.Build()
	File_generate_proto = out.File
	file_generate_proto_goTypes = nil
	file_generate_proto_depIdxs = nil
}
