// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: generate.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerationConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Temperature   *float32               `protobuf:"fixed32,1,opt,name=temperature,proto3,oneof" json:"temperature,omitempty"`
	TopP          *float32               `protobuf:"fixed32,2,opt,name=top_p,json=topP,proto3,oneof" json:"top_p,omitempty"`
	TopK          *float32               `protobuf:"fixed32,3,opt,name=top_k,json=topK,proto3,oneof" json:"top_k,omitempty"`
	OutputLength  *int32                 `protobuf:"varint,4,opt,name=output_length,json=outputLength,proto3,oneof" json:"output_length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerationConfig) Reset() {
	*x = GenerationConfig{}
	mi := &file_generate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerationConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerationConfig) ProtoMessage() {}

func (x *GenerationConfig) ProtoReflect() protoreflect.Message {
	mi := &file_generate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerationConfig.ProtoReflect.Descriptor instead.
func (*GenerationConfig) Descriptor() ([]byte, []int) {
	return file_generate_proto_rawDescGZIP(), []int{0}
}

func (x *GenerationConfig) GetTemperature() float32 {
	if x != nil && x.Temperature != nil {
		return *x.Temperature
	}
	return 0
}

func (x *GenerationConfig) GetTopP() float32 {
	if x != nil && x.TopP != nil {
		return *x.TopP
	}
	return 0
}

func (x *GenerationConfig) GetTopK() float32 {
	if x != nil && x.TopK != nil {
		return *x.TopK
	}
	return 0
}

func (x *GenerationConfig) GetOutputLength() int32 {
	if x != nil && x.OutputLength != nil {
		return *x.OutputLength
	}
	return 0
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	ModelCode     string                 `protobuf:"bytes,2,opt,name=model_code,json=modelCode,proto3" json:"model_code,omitempty"`
	Stream        bool                   `protobuf:"varint,3,opt,name=stream,proto3" json:"stream,omitempty"`
	Config        *GenerationConfig      `protobuf:"bytes,4,opt,name=config,proto3,oneof" json:"config,omitempty"`
	Images        [][]byte               `protobuf:"bytes,5,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_generate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_generate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_generate_proto_rawDescGZIP(), []int{1}
}

func (x *Request) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *Request) GetModelCode() string {
	if x != nil {
		return x.ModelCode
	}
	return ""
}

func (x *Request) GetStream() bool {
	if x != nil {
		return x.Stream
	}
	return false
}

func (x *Request) GetConfig() *GenerationConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *Request) GetImages() [][]byte {
	if x != nil {
		return x.Images
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OutputString  string                 `protobuf:"bytes,1,opt,name=output_string,json=outputString,proto3" json:"output_string,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_generate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_generate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_generate_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetOutputString() string {
	if x != nil {
		return x.OutputString
	}
	return ""
}

var File_generate_proto protoreflect.FileDescriptor

const file_generate_proto_rawDesc = "" +
	"\n" +
	"\x0egenerate.proto\x12\asynapse\"\xcd\x01\n" +
	"\x10GenerationConfig\x12%\n" +
	"\vtemperature\x18\x01 \x01(\x02H\x00R\vtemperature\x88\x01\x01\x12\x18\n" +
	"\x05top_p\x18\x02 \x01(\x02H\x01R\x04topP\x88\x01\x01\x12\x18\n" +
	"\x05top_k\x18\x03 \x01(\x02H\x02R\x04topK\x88\x01\x01\x12(\n" +
	"\routput_length\x18\x04 \x01(\x05H\x03R\foutputLength\x88\x01\x01B\x0e\n" +
	"\f_temperatureB\b\n" +
	"\x06_top_pB\b\n" +
	"\x06_top_kB\x10\n" +
	"\x0e_output_length\"\xb3\x01\n" +
	"\aRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12\x1d\n" +
	"\n" +
	"model_code\x18\x02 \x01(\tR\tmodelCode\x12\x16\n" +
	"\x06stream\x18\x03 \x01(\bR\x06stream\x126\n" +
	"\x06config\x18\x04 \x01(\v2\x19.synapse.GenerationConfigH\x00R\x06config\x88\x01\x01\x12\x16\n" +
	"\x06images\x18\x05 \x03(\fR\x06imagesB\t\n" +
	"\a_config\"/\n" +
	"\bResponse\x12#\n" +
	"\routput_string\x18\x01 \x01(\tR\foutputString2C\n" +
	"\bGenerate\x127\n" +
	"\fGenerateTask\x12\x10.synapse.Request\x1a\x11.synapse.Response\"\x000\x01B(Z&github.com/sokinpui/synapse.go/v2/grpcb\x06proto3"

var (
	file_generate_proto_rawDescOnce sync.Once
	file_generate_proto_rawDescData []byte
)

func file_generate_proto_rawDescGZIP() []byte {
	file_generate_proto_rawDescOnce.Do(func() {
		file_generate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_generate_proto_rawDesc), len(file_generate_proto_rawDesc)))
	})
	return file_generate_proto_rawDescData
}

var file_generate_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_generate_proto_goTypes = []any{
	(*GenerationConfig)(nil), // 0: synapse.GenerationConfig
	(*Request)(nil),          // 1: synapse.Request
	(*Response)(nil),         // 2: synapse.Response
}
var file_generate_proto_depIdxs = []int32{
	0, // 0: synapse.Request.config:type_name -> synapse.GenerationConfig
	1, // 1: synapse.Generate.GenerateTask:input_type -> synapse.Request
	2, // 2: synapse.Generate.GenerateTask:output_type -> synapse.Response
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_generate_proto_init() }
func file_generate_proto_init() {
	if File_generate_proto != nil {
		return
	}
	file_generate_proto_msgTypes[0].OneofWrappers = []any{}
	file_generate_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_generate_proto_rawDesc), len(file_generate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_generate_proto_goTypes,
		DependencyIndexes: file_generate_proto_depIdxs,
		MessageInfos:      file_generate_proto_msgTypes,
	}.Build()
	File_generate_proto = out.File
	file_generate_proto_goTypes = nil
	file_generate_proto_depIdxs = nil
}
