// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: generate.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Generate_GenerateTask_FullMethodName = "/synapse.Generate/GenerateTask"
)

// GenerateClient is the client API for Generate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GenerateClient interface {
	GenerateTask(ctx context.Context, in *Request, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Response], error)
}

type generateClient struct {
	cc grpc.ClientConnInterface
}

func NewGenerateClient(cc grpc.ClientConnInterface) GenerateClient {
	return &generateClient{cc}
}

func (c *generateClient) GenerateTask(ctx context.Context, in *Request, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Response], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Generate_ServiceDesc.Streams[0], Generate_GenerateTask_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Request, Response]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Generate_GenerateTaskClient = grpc.ServerStreamingClient[Response]

// GenerateServer is the server API for Generate service.
// All implementations must embed UnimplementedGenerateServer
// for forward compatibility.
type GenerateServer interface {
	GenerateTask(*Request, grpc.ServerStreamingServer[Response]) error
	mustEmbedUnimplementedGenerateServer()
}

// UnimplementedGenerateServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGenerateServer struct{}

func (UnimplementedGenerateServer) GenerateTask(*Request, grpc.ServerStreamingServer[Response]) error {
	return status.Errorf(codes.Unimplemented, "method GenerateTask not implemented")
}
func (UnimplementedGenerateServer) mustEmbedUnimplementedGenerateServer() {}
func (UnimplementedGenerateServer) testEmbeddedByValue()                  {}

// UnsafeGenerateServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GenerateServer will
// result in compilation errors.
type UnsafeGenerateServer interface {
	mustEmbedUnimplementedGenerateServer()
}

func RegisterGenerateServer(s grpc.ServiceRegistrar, srv GenerateServer) {
	// If the following call pancis, it indicates UnimplementedGenerateServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Generate_ServiceDesc, srv)
}

func _Generate_GenerateTask_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GenerateServer).GenerateTask(m, &grpc.GenericServerStream[Request, Response]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Generate_GenerateTaskServer = grpc.ServerStreamingServer[Response]

// Generate_ServiceDesc is the grpc.ServiceDesc for Generate service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Generate_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "synapse.Generate",
	HandlerType: (*GenerateServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GenerateTask",
			Handler:       _Generate_GenerateTask_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "generate.proto",
}
